### ISSUE TITLE
[README] 본인의 수행 역할 정리

### ISSUE THREAD

**Issue by Hooni07** [Sprint4Team16/Rolling#92]
해당  issues 항목 comment로 본인이 수행한 역할을 작성해주시면 되겠습니다.

(예시)
- (페이지 구현 내용) /post 구현
- (기능 구현 내용) API 기능 구현
- (기타 구현 사항 및 수행한 역할) README 파일 정리

## 관련 PR
#91

**Comment by Hooni07** [comment]
## <페이지 구현 내용>
- 롤링페이퍼 만들기 페이지 구현
    - 경로 : /post
- message 수정하기 페이지 구현
    - 경로 : /post/{recipientId}/edit/{messageId}

## <기능 구현 내용>
- API 기능 구현
    - POST, GET, POST, PATCH, DELETE 기능별 구성
    - 각 페이지, 버튼 기능별 API 연동
- Button 컴포넌트 생성 및 기능별 버튼 컴포넌트 생성
- color, 단위(px->rem) refactoring 진행

## <기타 수행 사항>
- 팀 repository 생성 및 issues, label 등 초기 세팅 설정
    - issues 항목 설정
    - label 카테고리 생성
- 팀 회의 기록 정리
- README 파일 생성 및 내용 정리

**Comment by youth-o** [comment]
## <페이지 구현 내용>
- 메인 페이지 구현
경로 : /

## <기능 구현 내용>
- Header 공용 컴포넌트 생성
- Modal 공용 컴포넌트 생성
- /post/{id} 페이지의 공유 버튼 구현
  - 카카오톡 공유 기능 
  - URL 복사 후 토스트
- /post/{id} 페이지의 작성자 프로필 이미지 불러오기

## <기타 수행 사항>
- PPT 자료 제작

**Comment by minjo0n61** [comment]
## <페이지 구현 내용>
- 생성된 롤링페이퍼 페이지 구현
    - 경로 : /post/{id}
- 생성된 롤링페이퍼 수정 페이지
    - 경로 : /post/{recipientId}/edit/

## <기능 구현 내용>
- 무한 스크롤 구현
    - intersection observer web API 사용하여 구현
- 이모티콘 추가 구현
    - 추가할 때마다 인기순으로 재정렬
    - emoji-picker-react 라이브러리 사용
- 카드 데이터 삭제 로직 구현
    - API 연동
- /post/{id}, /post/{id}/edit ui 구현 및 API 연동
    - 카드 구현
    - sub header 구현
    - 배경화면 변경되도록 구현
- Button 컴포넌트 생성 및 기능별 버튼 컴포넌트 생성

## <기타 수행 사항>
- 팀 초기 컨벤션 세팅 설정
    - .eslint.js 초기 설정
        - Airbnb 기준으로 제외할 rules 추가
    - .prettierrc 설정
- 페이지 별 team 작업 issue/trouble shooting/refactoring 사항에 관한 리스트 생성 및 관리

**Comment by gaeaeg** [comment]
## 페이지 구현 내용
- list 페이지 구현
  - 경로: /list

## 기능 구현 내용
- 카드 리스트
  - 인기순, 최신순으로 정렬
  - 터치 슬라이드 구현
- font설정 refactoring

**Comment by mangang0713** [comment]
## 페이지 구현 내용
- message 페이지 구현
  - 경로: /post/{id}/message
## 기능 구현 내용
- 외부 텍스트 에디터 활용
  - 에디터 툴 수정
- HTML 태그가 포함된 내용을 태그만 제거하여 호출
- font, color 공통화 작업
- Dropdown을 컴포넌트화 한 후 상이한 역할을 하도록 구현
